### ISSUE TITLE
Subdirectory

### ISSUE THREAD

**Issue by khanduras** [gibbs/phileBreadcrumbs#1]
It seems that phileBreadcrumbs doesn't take into account subdirectory installs.

**Comment by gibbs** [comment]
What isn't working? Both sites I'm using this in are in a subdirectory...

**Comment by khanduras** [comment]
Well I have two issues but maybe they're related. On a fresh install and activation, using twig and UI Kit [breadcrumbs](http://getuikit.com/docs/breadcrumb.html). The first breadcrumb linked to simply `/` which didn't consider the sub directory.

I added URL like you did with SubNav that was defined like 
    `$url = \Phile\Utility::getBaseUrl()  . $uri;`
Which makes that first page okay.
Now also, the only breadcrumb that shows is one page in particular. If I delete that page, another is selected. But only one no matter which page.

This is the twig code I'm currently using:

``` html
<ul class="uk-breadcrumb">
{% for crumb in breadcrumbs %}
{% if crumb.active %}
<li class="uk-active"><span>{{ crumb.meta.title }}</span></li>
{% else %}
<li><a href="{{ crumb.url }}">{{ crumb.meta.title }}</a></li>
{% endif %}
{% endfor %}
</ul>
```

**Comment by khanduras** [comment]
You can see an example here: http://puik.khanduras.net/

**Comment by gibbs** [comment]
I've just pushed a commit that simplifies this plugin and uses Phile to determine paths etc. It should resolve this. A 'url' attribute is also available for absolute urls.

**Comment by khanduras** [comment]
Man that works well. Thanks for the fix!

**Comment by khanduras** [comment]
I made a small change as the middle crumbs had a trailing `/` that was giving wrong links.

``` php
                $uri = rtrim($uri, '/');

                // Create the breadcrumb
                $breadcrumbs[] = array(
                    'active' => $crumb == end($path) ? true : false,
                    'meta'   => $current_page->getMeta()->getAll(),
                    'uri'    => $uri,
                    'url'    => \Phile\Utility::getBaseUrl() . $uri
                );
```

**Comment by gibbs** [comment]
Glad it worked. Twig also has a [trim](http://twig.sensiolabs.org/doc/filters/trim.html) function.
